/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedsIndexRouteImport } from './routes/feeds/index'
import { Route as FeedsIdRouteImport } from './routes/feeds/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIdRoute = FeedsIdRouteImport.update({
  id: '/feeds/$id',
  path: '/feeds/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds': typeof FeedsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feeds/$id' | '/feeds/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feeds/$id' | '/feeds'
  id: '__root__' | '/' | '/feeds/$id' | '/feeds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedsIdRoute: typeof FeedsIdRoute
  FeedsIndexRoute: typeof FeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$id': {
      id: '/feeds/$id'
      path: '/feeds/$id'
      fullPath: '/feeds/$id'
      preLoaderRoute: typeof FeedsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedsIdRoute: FeedsIdRoute,
  FeedsIndexRoute: FeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
